### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by MeycL** [neuraptic/cpe-clip#1]
A very exciting job! How can I run this code? If possible, could you provide more detailed instructions in the readme.md? Thank you very much.

**Comment by melkilin** [comment]
Thanks so much for your interest in our work @MeycL :smiley: 

We'll update [README.md](https://github.com/neuraptic/cpe-clip/blob/main/README.md) with further instructions ASAP.

**Comment by MeycL** [comment]
Thank you very much for your prompt response. I look forward to your more detailed updates.

**Comment by melkilin** [comment]
Closed by #2
